### ISSUE TITLE
Improve Graphite check output

### ISSUE THREAD

**Issue by mattmb** [ministryofjustice/sensu-formula#16]
We should improve the output of the graphite check. Right now it looks like:

![screen shot 2015-04-09 at 17 48 26](https://cloud.githubusercontent.com/assets/34150/7071988/d2b7753c-dee0-11e4-9e2f-dad6f2caa45f.png)

as text this is

> ALERT - [front-01.staging1.pvb/graphite-used-root-disk] - CheckGraphiteData CRITICAL: Root Disk Used Percentage (93.539437488085) [asPercent(metrics.pvb.staging1.front-01.df.root.df_complex.used, sumSeries(metrics.pvb.staging1.front-01.df.root.df_complex.{free,used}))]   [Graph].

 This could be improved by:

- Better formatting of numbers (percents to 2 dp, not 8+, bytes as GB,MB, not bytes)
- Remove metric/expression
- indication of below/above what threshold to match the community checks.

For this example something like this would be preferable:

> ALERT - [front-01.staging1.pvb/graphite-used-root-disk] - CheckGraphiteData CRITICAL: Root Disk Used Percentage is above the CRITICAL limit: 93.54% / 75% limit [Graph].

(With links to the graphs now having the name metric that was checked isn't useful anymore. `[Graph]` should be a link)

**Comment by niallcreech** [comment]
Graphite check alert output is quite verbose. This will add a --pretty
option to the graphite plugin, which makes the plugin try to produce
a simpler and more clear output. For example

    A simpler message
    Percents to 2 decimal places rather than 8+
    Percent signs for percent units

The complex raw message is similar to
ALERT - [front-01.staging1.pvb/graphite-used-root-disk]

    CheckGraphiteData CRITICAL: Root Disk Used Percentage (93.539437488085) [asPercent(metrics.pvb.staging1.front-01.df.root.df_complex.used, sumSeries(metrics.pvb.staging1.front-01.df.root.df_complex.{free,used}))]

When the --pretty option is passed this becomes
CheckGraphiteData CRITICAL: Root Disk Used Percentage is above critical limit: 98.5% / 95.0%

**Comment by niallcreech** [comment]
https://github.com/ministryofjustice/sensu-formula/pull/82
